/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CoachNotificationAdditionalInfo } from './coachNotificationAdditionalInfo';

export class CoachNotification {
    'type': CoachNotification.TypeEnum;
    'message': string;
    'additionalInfo'?: CoachNotificationAdditionalInfo;
    'dateCreated': string;
    'read': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CoachNotification.TypeEnum"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "additionalInfo",
            "baseName": "additionalInfo",
            "type": "CoachNotificationAdditionalInfo"
        },
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "string"
        },
        {
            "name": "read",
            "baseName": "read",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return CoachNotification.attributeTypeMap;
    }
}

export namespace CoachNotification {
    export enum TypeEnum {
        LessonApproved = <any> 'Lesson approved',
        LessonCancelled = <any> 'Lesson cancelled',
        LessonDeclined = <any> 'Lesson declined',
        PaymentUpdate = <any> 'Payment update',
        Announcement = <any> 'Announcement',
        TrainingReport = <any> 'Training report',
        Reviews = <any> 'Reviews'
    }
}
