/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CoachProfileCredentialsAndExperience {
    'extensiveCoachingExperience'?: string;
    'industryRecognition'?: string;
    'trustedByStudents'?: string;
    'specializationNotes'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "extensiveCoachingExperience",
            "baseName": "extensiveCoachingExperience",
            "type": "string"
        },
        {
            "name": "industryRecognition",
            "baseName": "industryRecognition",
            "type": "string"
        },
        {
            "name": "trustedByStudents",
            "baseName": "trustedByStudents",
            "type": "string"
        },
        {
            "name": "specializationNotes",
            "baseName": "specializationNotes",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CoachProfileCredentialsAndExperience.attributeTypeMap;
    }
}

