/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CoachSessionProvided } from './coachSessionProvided';
import { CoachSessionWhatToBring } from './coachSessionWhatToBring';

export class CoachSession {
    'sport': CoachSession.SportEnum;
    'sessionPlan': string;
    'provided': CoachSessionProvided;
    'whatToBring': CoachSessionWhatToBring;
    'sessionType': CoachSession.SessionTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sport",
            "baseName": "sport",
            "type": "CoachSession.SportEnum"
        },
        {
            "name": "sessionPlan",
            "baseName": "sessionPlan",
            "type": "string"
        },
        {
            "name": "provided",
            "baseName": "provided",
            "type": "CoachSessionProvided"
        },
        {
            "name": "whatToBring",
            "baseName": "whatToBring",
            "type": "CoachSessionWhatToBring"
        },
        {
            "name": "sessionType",
            "baseName": "sessionType:",
            "type": "CoachSession.SessionTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return CoachSession.attributeTypeMap;
    }
}

export namespace CoachSession {
    export enum SportEnum {
        Tennis = <any> 'tennis'
    }
    export enum SessionTypeEnum {
        _1On1 = <any> '1-on-1'
    }
}
