/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CoachAvailabilityLocation } from './coachAvailabilityLocation';

export class CoachAvailability {
    'date': string;
    'startTime': Date;
    'endTime': string;
    'location': CoachAvailabilityLocation;
    'repetition': CoachAvailability.RepetitionEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "Date"
        },
        {
            "name": "endTime",
            "baseName": "endTime",
            "type": "string"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "CoachAvailabilityLocation"
        },
        {
            "name": "repetition",
            "baseName": "repetition",
            "type": "CoachAvailability.RepetitionEnum"
        }    ];

    static getAttributeTypeMap() {
        return CoachAvailability.attributeTypeMap;
    }
}

export namespace CoachAvailability {
    export enum RepetitionEnum {
        RepeatsWeekly = <any> 'Repeats weekly',
        RepeatsMonthly = <any> 'Repeats monthly',
        DoesNotRepeat = <any> 'Does not repeat'
    }
}
