/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CoachSessionPutProvided } from './coachSessionPutProvided';
import { CoachSessionPutWhatToBring } from './coachSessionPutWhatToBring';

export class CoachSessionPut {
    'sport': CoachSessionPut.SportEnum;
    'sessionPlan'?: string;
    'provided'?: CoachSessionPutProvided;
    'whatToBring'?: CoachSessionPutWhatToBring;
    'sessionType': CoachSessionPut.SessionTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sport",
            "baseName": "sport",
            "type": "CoachSessionPut.SportEnum"
        },
        {
            "name": "sessionPlan",
            "baseName": "sessionPlan",
            "type": "string"
        },
        {
            "name": "provided",
            "baseName": "provided",
            "type": "CoachSessionPutProvided"
        },
        {
            "name": "whatToBring",
            "baseName": "whatToBring",
            "type": "CoachSessionPutWhatToBring"
        },
        {
            "name": "sessionType",
            "baseName": "sessionType:",
            "type": "CoachSessionPut.SessionTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return CoachSessionPut.attributeTypeMap;
    }
}

export namespace CoachSessionPut {
    export enum SportEnum {
        Tennis = <any> 'tennis'
    }
    export enum SessionTypeEnum {
        _1On1 = <any> '1-on-1'
    }
}
