/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CoachProfileAboutMe } from './coachProfileAboutMe';
import { CoachProfileCertificates } from './coachProfileCertificates';
import { CoachProfileCredentialsAndExperience } from './coachProfileCredentialsAndExperience';
import { CoachProfileFaq } from './coachProfileFaq';
import { CoachProfileTrainingLocations } from './coachProfileTrainingLocations';

export class CoachProfile {
    'name': string;
    'pricePerHr': number;
    'sport': CoachProfile.SportEnum;
    'gender': CoachProfile.GenderEnum;
    'aboutMe': CoachProfileAboutMe;
    'credentialsAndExperience': CoachProfileCredentialsAndExperience;
    'photos'?: Array<string>;
    'certificates': Set<CoachProfileCertificates>;
    'trainingLocations': Set<CoachProfileTrainingLocations>;
    'faq'?: Set<CoachProfileFaq>;
    'video'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "pricePerHr",
            "baseName": "pricePerHr",
            "type": "number"
        },
        {
            "name": "sport",
            "baseName": "sport",
            "type": "CoachProfile.SportEnum"
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "CoachProfile.GenderEnum"
        },
        {
            "name": "aboutMe",
            "baseName": "aboutMe",
            "type": "CoachProfileAboutMe"
        },
        {
            "name": "credentialsAndExperience",
            "baseName": "credentialsAndExperience",
            "type": "CoachProfileCredentialsAndExperience"
        },
        {
            "name": "photos",
            "baseName": "photos",
            "type": "Array<string>"
        },
        {
            "name": "certificates",
            "baseName": "certificates",
            "type": "Set<CoachProfileCertificates>"
        },
        {
            "name": "trainingLocations",
            "baseName": "trainingLocations",
            "type": "Set<CoachProfileTrainingLocations>"
        },
        {
            "name": "faq",
            "baseName": "faq",
            "type": "Set<CoachProfileFaq>"
        },
        {
            "name": "video",
            "baseName": "video",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CoachProfile.attributeTypeMap;
    }
}

export namespace CoachProfile {
    export enum SportEnum {
        Tennis = <any> 'Tennis'
    }
    export enum GenderEnum {
        Male = <any> 'Male',
        Female = <any> 'Female',
        Others = <any> 'Others'
    }
}
