/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CoachProfileSettingsPrivacyResetPassword {
    'currentPassword': string;
    'newPassword1': string;
    'newPassword2': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "currentPassword",
            "baseName": "currentPassword",
            "type": "string"
        },
        {
            "name": "newPassword1",
            "baseName": "newPassword1",
            "type": "string"
        },
        {
            "name": "newPassword2",
            "baseName": "newPassword2",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CoachProfileSettingsPrivacyResetPassword.attributeTypeMap;
    }
}

