/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FilterSpecialties {
    'skillLevel'?: Set<FilterSpecialties.SkillLevelEnum>;
    'ageRange'?: Set<FilterSpecialties.AgeRangeEnum>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "skillLevel",
            "baseName": "skillLevel",
            "type": "Set<FilterSpecialties.SkillLevelEnum>"
        },
        {
            "name": "ageRange",
            "baseName": "ageRange",
            "type": "Set<FilterSpecialties.AgeRangeEnum>"
        }    ];

    static getAttributeTypeMap() {
        return FilterSpecialties.attributeTypeMap;
    }
}

export namespace FilterSpecialties {
    export enum SkillLevelEnum {
        Beginner = <any> 'Beginner',
        Intermediate = <any> 'Intermediate',
        Competitive = <any> 'Competitive',
        Advanced = <any> 'Advanced'
    }
    export enum AgeRangeEnum {
        Kids = <any> 'Kids',
        Juniors = <any> 'Juniors',
        Adults = <any> 'Adults',
        Seniors = <any> 'Seniors'
    }
}
