/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FilterFocusTags } from './filterFocusTags';
import { FilterPriceRange } from './filterPriceRange';
import { FilterSchedule } from './filterSchedule';
import { FilterSpecialties } from './filterSpecialties';

/**
* Single user saved filter
*/
export class Filter {
    'filterName': string;
    'focusTags'?: Set<FilterFocusTags>;
    'priceRange'?: FilterPriceRange;
    'distance'?: number;
    'schedule'?: FilterSchedule;
    'gender'?: Filter.GenderEnum;
    'specialties'?: FilterSpecialties;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "filterName",
            "baseName": "filterName",
            "type": "string"
        },
        {
            "name": "focusTags",
            "baseName": "focusTags",
            "type": "Set<FilterFocusTags>"
        },
        {
            "name": "priceRange",
            "baseName": "priceRange",
            "type": "FilterPriceRange"
        },
        {
            "name": "distance",
            "baseName": "distance",
            "type": "number"
        },
        {
            "name": "schedule",
            "baseName": "schedule",
            "type": "FilterSchedule"
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "Filter.GenderEnum"
        },
        {
            "name": "specialties",
            "baseName": "specialties",
            "type": "FilterSpecialties"
        }    ];

    static getAttributeTypeMap() {
        return Filter.attributeTypeMap;
    }
}

export namespace Filter {
    export enum GenderEnum {
        Any = <any> 'Any',
        Female = <any> 'Female',
        Male = <any> 'Male',
        Others = <any> 'Others'
    }
}
