/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FilterSchedule {
    'timeOfTheDay'?: Set<FilterSchedule.TimeOfTheDayEnum>;
    'dayOfTheWeek'?: Set<FilterSchedule.DayOfTheWeekEnum>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timeOfTheDay",
            "baseName": "timeOfTheDay",
            "type": "Set<FilterSchedule.TimeOfTheDayEnum>"
        },
        {
            "name": "dayOfTheWeek",
            "baseName": "dayOfTheWeek",
            "type": "Set<FilterSchedule.DayOfTheWeekEnum>"
        }    ];

    static getAttributeTypeMap() {
        return FilterSchedule.attributeTypeMap;
    }
}

export namespace FilterSchedule {
    export enum TimeOfTheDayEnum {
        Morning = <any> 'Morning',
        LateMorning = <any> 'Late Morning',
        Afternoon = <any> 'Afternoon',
        LateAfternoon = <any> 'Late Afternoon',
        Evening = <any> 'Evening',
        LateEvening = <any> 'Late Evening'
    }
    export enum DayOfTheWeekEnum {
        Sun = <any> 'Sun',
        Mon = <any> 'Mon',
        Tue = <any> 'Tue',
        Wed = <any> 'Wed',
        Thu = <any> 'Thu',
        Fri = <any> 'Fri',
        Sat = <any> 'Sat'
    }
}
