/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FilterFocusTags {
    'sport'?: FilterFocusTags.SportEnum;
    'skill'?: FilterFocusTags.SkillEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sport",
            "baseName": "sport",
            "type": "FilterFocusTags.SportEnum"
        },
        {
            "name": "skill",
            "baseName": "skill",
            "type": "FilterFocusTags.SkillEnum"
        }    ];

    static getAttributeTypeMap() {
        return FilterFocusTags.attributeTypeMap;
    }
}

export namespace FilterFocusTags {
    export enum SportEnum {
        Tennis = <any> 'Tennis'
    }
    export enum SkillEnum {
        Forehand = <any> 'Forehand',
        Backhand = <any> 'Backhand',
        TopSpin = <any> 'Top Spin',
        Serve = <any> 'Serve',
        Volley = <any> 'Volley'
    }
}
