/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { InlineResponse2006TopCities } from './inlineResponse2006TopCities';
import { InlineResponse2006TopStates } from './inlineResponse2006TopStates';

export class InlineResponse2006 {
    'topStates'?: Array<InlineResponse2006TopStates>;
    'topCities'?: Array<InlineResponse2006TopCities>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "topStates",
            "baseName": "topStates",
            "type": "Array<InlineResponse2006TopStates>"
        },
        {
            "name": "topCities",
            "baseName": "topCities",
            "type": "Array<InlineResponse2006TopCities>"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2006.attributeTypeMap;
    }
}

