/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineResponse20010 {
    'name'?: string;
    'userType'?: InlineResponse20010.UserTypeEnum;
    'rating'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "userType",
            "baseName": "userType",
            "type": "InlineResponse20010.UserTypeEnum"
        },
        {
            "name": "rating",
            "baseName": "rating",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20010.attributeTypeMap;
    }
}

export namespace InlineResponse20010 {
    export enum UserTypeEnum {
        Coach = <any> 'coach',
        Student = <any> 'student'
    }
}
