/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineObject9 {
    'certificateId': string;
    'result': InlineObject9.ResultEnum;
    'reasonIfDeclined'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "certificateId",
            "baseName": "certificateId",
            "type": "string"
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "InlineObject9.ResultEnum"
        },
        {
            "name": "reasonIfDeclined",
            "baseName": "reasonIfDeclined",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InlineObject9.attributeTypeMap;
    }
}

export namespace InlineObject9 {
    export enum ResultEnum {
        Approved = <any> 'approved',
        Declined = <any> 'declined'
    }
}
