/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineResponse20011 {
    'userId'?: string;
    'userName'?: string;
    'numCertificates'?: number;
    'status'?: InlineResponse20011.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string"
        },
        {
            "name": "numCertificates",
            "baseName": "numCertificates",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "InlineResponse20011.StatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse20011.attributeTypeMap;
    }
}

export namespace InlineResponse20011 {
    export enum StatusEnum {
        Pending = <any> 'pending',
        Declined = <any> 'declined',
        Approved = <any> 'approved'
    }
}
