/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineObject3 {
    'cardNumber': string;
    'expirationDate': string;
    'cVV': string;
    'cardType': InlineObject3.CardTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cardNumber",
            "baseName": "cardNumber",
            "type": "string"
        },
        {
            "name": "expirationDate",
            "baseName": "expirationDate",
            "type": "string"
        },
        {
            "name": "cVV",
            "baseName": "CVV",
            "type": "string"
        },
        {
            "name": "cardType",
            "baseName": "cardType",
            "type": "InlineObject3.CardTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return InlineObject3.attributeTypeMap;
    }
}

export namespace InlineObject3 {
    export enum CardTypeEnum {
        Visa = <any> 'Visa',
        MasterCard = <any> 'MasterCard',
        AmericanExpress = <any> 'American Express',
        DinersClub = <any> 'Diners Club',
        Discover = <any> 'Discover',
        Jcb = <any> 'JCB'
    }
}
