/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InlineResponse2002 {
    'incomeThisWeek'?: number;
    'hoursWorked'?: number;
    'numSessions'?: number;
    'numStudents'?: number;
    'data'?: Array<object>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "incomeThisWeek",
            "baseName": "incomeThisWeek",
            "type": "number"
        },
        {
            "name": "hoursWorked",
            "baseName": "hoursWorked",
            "type": "number"
        },
        {
            "name": "numSessions",
            "baseName": "numSessions",
            "type": "number"
        },
        {
            "name": "numStudents",
            "baseName": "numStudents",
            "type": "number"
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<object>"
        }    ];

    static getAttributeTypeMap() {
        return InlineResponse2002.attributeTypeMap;
    }
}

