/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* This is the payload to use to submit a lesson cancel request.
*/
export class LessonCancelRequest {
    'cancelReason': LessonCancelRequest.CancelReasonEnum;
    'optionalComment'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cancelReason",
            "baseName": "cancelReason",
            "type": "LessonCancelRequest.CancelReasonEnum"
        },
        {
            "name": "optionalComment",
            "baseName": "optionalComment",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return LessonCancelRequest.attributeTypeMap;
    }
}

export namespace LessonCancelRequest {
    export enum CancelReasonEnum {
        MedicalEmergency = <any> 'Medical emergency',
        Weather = <any> 'Weather',
        Other = <any> 'Other'
    }
}
