/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LessonStudentInfo } from './lessonStudentInfo';

/**
* Lesson Model
*/
export class Lesson {
    'lessonId': string;
    'lessonType': Lesson.LessonTypeEnum;
    'startTime': Date;
    'endTime': Date;
    'locationId': string;
    'coachId': string;
    'bookerId': string;
    'paymentMethodId': string;
    'status': Lesson.StatusEnum;
    'studentInfo'?: LessonStudentInfo;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "lessonId",
            "baseName": "lessonId",
            "type": "string"
        },
        {
            "name": "lessonType",
            "baseName": "lessonType",
            "type": "Lesson.LessonTypeEnum"
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "Date"
        },
        {
            "name": "endTime",
            "baseName": "endTime",
            "type": "Date"
        },
        {
            "name": "locationId",
            "baseName": "locationId",
            "type": "string"
        },
        {
            "name": "coachId",
            "baseName": "coachId",
            "type": "string"
        },
        {
            "name": "bookerId",
            "baseName": "bookerId",
            "type": "string"
        },
        {
            "name": "paymentMethodId",
            "baseName": "paymentMethodId",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "Lesson.StatusEnum"
        },
        {
            "name": "studentInfo",
            "baseName": "studentInfo",
            "type": "LessonStudentInfo"
        }    ];

    static getAttributeTypeMap() {
        return Lesson.attributeTypeMap;
    }
}

export namespace Lesson {
    export enum LessonTypeEnum {
        _1On1 = <any> '1-on-1'
    }
    export enum StatusEnum {
        Pending = <any> 'pending',
        Accepted = <any> 'accepted',
        Rejected = <any> 'rejected',
        Cancelled = <any> 'cancelled'
    }
}
