/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StudentProfilePostExperience } from './studentProfilePostExperience';
import { StudentProfilePostNotificationSettings } from './studentProfilePostNotificationSettings';
import { StudentProfilePostPaymentMethods } from './studentProfilePostPaymentMethods';

/**
* Student profile info
*/
export class StudentProfilePost {
    'studentId': string;
    'profileImage': string;
    'fullName': string;
    'phoneNumber': string;
    'gender'?: StudentProfilePost.GenderEnum;
    'dateOfBirth': string;
    'emailAddress': string;
    'aboutMe': string;
    'experience': Array<StudentProfilePostExperience>;
    'paymentMethods': Set<StudentProfilePostPaymentMethods>;
    'notificationSettings': StudentProfilePostNotificationSettings;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "studentId",
            "baseName": "studentId",
            "type": "string"
        },
        {
            "name": "profileImage",
            "baseName": "profileImage",
            "type": "string"
        },
        {
            "name": "fullName",
            "baseName": "fullName",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string"
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "StudentProfilePost.GenderEnum"
        },
        {
            "name": "dateOfBirth",
            "baseName": "dateOfBirth",
            "type": "string"
        },
        {
            "name": "emailAddress",
            "baseName": "emailAddress",
            "type": "string"
        },
        {
            "name": "aboutMe",
            "baseName": "aboutMe",
            "type": "string"
        },
        {
            "name": "experience",
            "baseName": "experience",
            "type": "Array<StudentProfilePostExperience>"
        },
        {
            "name": "paymentMethods",
            "baseName": "paymentMethods",
            "type": "Set<StudentProfilePostPaymentMethods>"
        },
        {
            "name": "notificationSettings",
            "baseName": "notificationSettings",
            "type": "StudentProfilePostNotificationSettings"
        }    ];

    static getAttributeTypeMap() {
        return StudentProfilePost.attributeTypeMap;
    }
}

export namespace StudentProfilePost {
    export enum GenderEnum {
        Male = <any> 'Male',
        Female = <any> 'Female'
    }
}
