/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class StudentProfilePaymentMethods {
    '_default'?: boolean = true;
    'paymentMethodId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "_default",
            "baseName": "default",
            "type": "boolean"
        },
        {
            "name": "paymentMethodId",
            "baseName": "paymentMethodId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return StudentProfilePaymentMethods.attributeTypeMap;
    }
}

