/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class StudentProfilePostNotificationSettings {
    'messageMe': Array<boolean>;
    'leftReview': Array<boolean>;
    'cancelledLesson': Array<boolean>;
    'acceptOrDeclineLesson': Array<boolean>;
    'getNewsAndUpdates': Array<boolean>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "messageMe",
            "baseName": "messageMe",
            "type": "Array<boolean>"
        },
        {
            "name": "leftReview",
            "baseName": "LeftReview",
            "type": "Array<boolean>"
        },
        {
            "name": "cancelledLesson",
            "baseName": "cancelledLesson",
            "type": "Array<boolean>"
        },
        {
            "name": "acceptOrDeclineLesson",
            "baseName": "acceptOrDeclineLesson",
            "type": "Array<boolean>"
        },
        {
            "name": "getNewsAndUpdates",
            "baseName": "getNewsAndUpdates",
            "type": "Array<boolean>"
        }    ];

    static getAttributeTypeMap() {
        return StudentProfilePostNotificationSettings.attributeTypeMap;
    }
}

