/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StudentProfileExperience } from './studentProfileExperience';
import { StudentProfileNotificationSettings } from './studentProfileNotificationSettings';
import { StudentProfilePaymentMethods } from './studentProfilePaymentMethods';

/**
* Student profile info
*/
export class StudentProfile {
    'profileImage'?: string;
    'fullName'?: string;
    'phoneNumber'?: string;
    'gender'?: StudentProfile.GenderEnum;
    'dateOfBirth'?: string;
    'emailAddress'?: string;
    'aboutMe'?: string;
    'experience'?: Array<StudentProfileExperience>;
    'paymentMethods'?: Set<StudentProfilePaymentMethods>;
    'notificationSettings'?: StudentProfileNotificationSettings;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "profileImage",
            "baseName": "profileImage",
            "type": "string"
        },
        {
            "name": "fullName",
            "baseName": "fullName",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string"
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "StudentProfile.GenderEnum"
        },
        {
            "name": "dateOfBirth",
            "baseName": "dateOfBirth",
            "type": "string"
        },
        {
            "name": "emailAddress",
            "baseName": "emailAddress",
            "type": "string"
        },
        {
            "name": "aboutMe",
            "baseName": "aboutMe",
            "type": "string"
        },
        {
            "name": "experience",
            "baseName": "experience",
            "type": "Array<StudentProfileExperience>"
        },
        {
            "name": "paymentMethods",
            "baseName": "paymentMethods",
            "type": "Set<StudentProfilePaymentMethods>"
        },
        {
            "name": "notificationSettings",
            "baseName": "notificationSettings",
            "type": "StudentProfileNotificationSettings"
        }    ];

    static getAttributeTypeMap() {
        return StudentProfile.attributeTypeMap;
    }
}

export namespace StudentProfile {
    export enum GenderEnum {
        Male = <any> 'Male',
        Female = <any> 'Female'
    }
}
