/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CoachAvailabilityLocation model module.
 * @module model/CoachAvailabilityLocation
 * @version 1.0.0
 */
class CoachAvailabilityLocation {
    /**
     * Constructs a new <code>CoachAvailabilityLocation</code>.
     * @alias module:model/CoachAvailabilityLocation
     * @param name {String} 
     * @param locationId {String} 
     */
    constructor(name, locationId) { 
        
        CoachAvailabilityLocation.initialize(this, name, locationId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, locationId) { 
        obj['name'] = name;
        obj['locationId'] = locationId;
    }

    /**
     * Constructs a <code>CoachAvailabilityLocation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CoachAvailabilityLocation} obj Optional instance to populate.
     * @return {module:model/CoachAvailabilityLocation} The populated <code>CoachAvailabilityLocation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CoachAvailabilityLocation();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('locationId')) {
                obj['locationId'] = ApiClient.convertToType(data['locationId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
CoachAvailabilityLocation.prototype['name'] = undefined;

/**
 * @member {String} locationId
 */
CoachAvailabilityLocation.prototype['locationId'] = undefined;






export default CoachAvailabilityLocation;

