/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CoachAvailabilityLocation from './CoachAvailabilityLocation';

/**
 * The CoachAvailabilityPut model module.
 * @module model/CoachAvailabilityPut
 * @version 1.0.4
 */
class CoachAvailabilityPut {
    /**
     * Constructs a new <code>CoachAvailabilityPut</code>.
     * @alias module:model/CoachAvailabilityPut
     */
    constructor() { 
        
        CoachAvailabilityPut.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CoachAvailabilityPut</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CoachAvailabilityPut} obj Optional instance to populate.
     * @return {module:model/CoachAvailabilityPut} The populated <code>CoachAvailabilityPut</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CoachAvailabilityPut();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('startTime')) {
                obj['startTime'] = ApiClient.convertToType(data['startTime'], 'Date');
            }
            if (data.hasOwnProperty('endTime')) {
                obj['endTime'] = ApiClient.convertToType(data['endTime'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = CoachAvailabilityLocation.constructFromObject(data['location']);
            }
            if (data.hasOwnProperty('repetition')) {
                obj['repetition'] = ApiClient.convertToType(data['repetition'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} date
 */
CoachAvailabilityPut.prototype['date'] = undefined;

/**
 * @member {Date} startTime
 */
CoachAvailabilityPut.prototype['startTime'] = undefined;

/**
 * @member {String} endTime
 */
CoachAvailabilityPut.prototype['endTime'] = undefined;

/**
 * @member {module:model/CoachAvailabilityLocation} location
 */
CoachAvailabilityPut.prototype['location'] = undefined;

/**
 * @member {module:model/CoachAvailabilityPut.RepetitionEnum} repetition
 */
CoachAvailabilityPut.prototype['repetition'] = undefined;





/**
 * Allowed values for the <code>repetition</code> property.
 * @enum {String}
 * @readonly
 */
CoachAvailabilityPut['RepetitionEnum'] = {

    /**
     * value: "Repeats weekly"
     * @const
     */
    "Repeats weekly": "Repeats weekly",

    /**
     * value: "Repeats monthly"
     * @const
     */
    "Repeats monthly": "Repeats monthly",

    /**
     * value: "Does not repeat"
     * @const
     */
    "Does not repeat": "Does not repeat"
};



export default CoachAvailabilityPut;

