/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CoachProfileAboutMe model module.
 * @module model/CoachProfileAboutMe
 * @version 1.0.0
 */
class CoachProfileAboutMe {
    /**
     * Constructs a new <code>CoachProfileAboutMe</code>.
     * @alias module:model/CoachProfileAboutMe
     */
    constructor() { 
        
        CoachProfileAboutMe.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CoachProfileAboutMe</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CoachProfileAboutMe} obj Optional instance to populate.
     * @return {module:model/CoachProfileAboutMe} The populated <code>CoachProfileAboutMe</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CoachProfileAboutMe();

            if (data.hasOwnProperty('bio')) {
                obj['bio'] = ApiClient.convertToType(data['bio'], 'String');
            }
            if (data.hasOwnProperty('teaches')) {
                obj['teaches'] = ApiClient.convertToType(data['teaches'], ['String']);
            }
            if (data.hasOwnProperty('levels')) {
                obj['levels'] = ApiClient.convertToType(data['levels'], ['String']);
            }
            if (data.hasOwnProperty('specialization')) {
                obj['specialization'] = ApiClient.convertToType(data['specialization'], ['String']);
            }
            if (data.hasOwnProperty('fastResponseRate')) {
                obj['fastResponseRate'] = ApiClient.convertToType(data['fastResponseRate'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} bio
 */
CoachProfileAboutMe.prototype['bio'] = undefined;

/**
 * @member {Array.<module:model/CoachProfileAboutMe.TeachesEnum>} teaches
 */
CoachProfileAboutMe.prototype['teaches'] = undefined;

/**
 * @member {Array.<module:model/CoachProfileAboutMe.LevelsEnum>} levels
 */
CoachProfileAboutMe.prototype['levels'] = undefined;

/**
 * @member {Array.<module:model/CoachProfileAboutMe.SpecializationEnum>} specialization
 */
CoachProfileAboutMe.prototype['specialization'] = undefined;

/**
 * @member {Number} fastResponseRate
 */
CoachProfileAboutMe.prototype['fastResponseRate'] = undefined;





/**
 * Allowed values for the <code>teaches</code> property.
 * @enum {String}
 * @readonly
 */
CoachProfileAboutMe['TeachesEnum'] = {

    /**
     * value: "Kids"
     * @const
     */
    "Kids": "Kids",

    /**
     * value: "Juniors"
     * @const
     */
    "Juniors": "Juniors",

    /**
     * value: "Adults"
     * @const
     */
    "Adults": "Adults",

    /**
     * value: "Seniors"
     * @const
     */
    "Seniors": "Seniors"
};


/**
 * Allowed values for the <code>levels</code> property.
 * @enum {String}
 * @readonly
 */
CoachProfileAboutMe['LevelsEnum'] = {

    /**
     * value: "Beginner"
     * @const
     */
    "Beginner": "Beginner",

    /**
     * value: "Intermediate"
     * @const
     */
    "Intermediate": "Intermediate",

    /**
     * value: "Advanced"
     * @const
     */
    "Advanced": "Advanced"
};


/**
 * Allowed values for the <code>specialization</code> property.
 * @enum {String}
 * @readonly
 */
CoachProfileAboutMe['SpecializationEnum'] = {

    /**
     * value: "Forehand"
     * @const
     */
    "Forehand": "Forehand",

    /**
     * value: "Backhand"
     * @const
     */
    "Backhand": "Backhand",

    /**
     * value: "Top Spin"
     * @const
     */
    "Top Spin": "Top Spin",

    /**
     * value: "Volley"
     * @const
     */
    "Volley": "Volley",

    /**
     * value: "Lob"
     * @const
     */
    "Lob": "Lob",

    /**
     * value: "Serve"
     * @const
     */
    "Serve": "Serve"
};



export default CoachProfileAboutMe;

