/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CoachNotificationAdditionalInfoLessonInfo from './CoachNotificationAdditionalInfoLessonInfo';

/**
 * The CoachNotificationAdditionalInfo model module.
 * @module model/CoachNotificationAdditionalInfo
 * @version 1.0.4
 */
class CoachNotificationAdditionalInfo {
    /**
     * Constructs a new <code>CoachNotificationAdditionalInfo</code>.
     * @alias module:model/CoachNotificationAdditionalInfo
     */
    constructor() { 
        
        CoachNotificationAdditionalInfo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CoachNotificationAdditionalInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CoachNotificationAdditionalInfo} obj Optional instance to populate.
     * @return {module:model/CoachNotificationAdditionalInfo} The populated <code>CoachNotificationAdditionalInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CoachNotificationAdditionalInfo();

            if (data.hasOwnProperty('lessonInfo')) {
                obj['lessonInfo'] = CoachNotificationAdditionalInfoLessonInfo.constructFromObject(data['lessonInfo']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CoachNotificationAdditionalInfoLessonInfo} lessonInfo
 */
CoachNotificationAdditionalInfo.prototype['lessonInfo'] = undefined;






export default CoachNotificationAdditionalInfo;

