/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CoachNotificationAdditionalInfo from './CoachNotificationAdditionalInfo';

/**
 * The CoachNotification model module.
 * @module model/CoachNotification
 * @version 1.0.7
 */
class CoachNotification {
    /**
     * Constructs a new <code>CoachNotification</code>.
     * @alias module:model/CoachNotification
     * @param type {module:model/CoachNotification.TypeEnum} 
     * @param message {String} 
     * @param dateCreated {Date} 
     * @param read {Boolean} 
     */
    constructor(type, message, dateCreated, read) { 
        
        CoachNotification.initialize(this, type, message, dateCreated, read);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, message, dateCreated, read) { 
        obj['type'] = type;
        obj['message'] = message;
        obj['dateCreated'] = dateCreated;
        obj['read'] = read;
    }

    /**
     * Constructs a <code>CoachNotification</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CoachNotification} obj Optional instance to populate.
     * @return {module:model/CoachNotification} The populated <code>CoachNotification</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CoachNotification();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('additionalInfo')) {
                obj['additionalInfo'] = CoachNotificationAdditionalInfo.constructFromObject(data['additionalInfo']);
            }
            if (data.hasOwnProperty('dateCreated')) {
                obj['dateCreated'] = ApiClient.convertToType(data['dateCreated'], 'Date');
            }
            if (data.hasOwnProperty('read')) {
                obj['read'] = ApiClient.convertToType(data['read'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/CoachNotification.TypeEnum} type
 */
CoachNotification.prototype['type'] = undefined;

/**
 * @member {String} message
 */
CoachNotification.prototype['message'] = undefined;

/**
 * @member {module:model/CoachNotificationAdditionalInfo} additionalInfo
 */
CoachNotification.prototype['additionalInfo'] = undefined;

/**
 * @member {Date} dateCreated
 */
CoachNotification.prototype['dateCreated'] = undefined;

/**
 * @member {Boolean} read
 */
CoachNotification.prototype['read'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
CoachNotification['TypeEnum'] = {

    /**
     * value: "Lesson approved"
     * @const
     */
    "Lesson approved": "Lesson approved",

    /**
     * value: "Lesson cancelled"
     * @const
     */
    "Lesson cancelled": "Lesson cancelled",

    /**
     * value: "Lesson declined"
     * @const
     */
    "Lesson declined": "Lesson declined",

    /**
     * value: "Payment update"
     * @const
     */
    "Payment update": "Payment update",

    /**
     * value: "Announcement"
     * @const
     */
    "Announcement": "Announcement",

    /**
     * value: "Training report"
     * @const
     */
    "Training report": "Training report",

    /**
     * value: "Reviews"
     * @const
     */
    "Reviews": "Reviews"
};



export default CoachNotification;

