/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CoachProfileTrainingLocations model module.
 * @module model/CoachProfileTrainingLocations
 * @version 1.0.0
 */
class CoachProfileTrainingLocations {
    /**
     * Constructs a new <code>CoachProfileTrainingLocations</code>.
     * @alias module:model/CoachProfileTrainingLocations
     * @param name {String} 
     * @param address {String} 
     */
    constructor(name, address) { 
        
        CoachProfileTrainingLocations.initialize(this, name, address);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, address) { 
        obj['name'] = name;
        obj['address'] = address;
    }

    /**
     * Constructs a <code>CoachProfileTrainingLocations</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CoachProfileTrainingLocations} obj Optional instance to populate.
     * @return {module:model/CoachProfileTrainingLocations} The populated <code>CoachProfileTrainingLocations</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CoachProfileTrainingLocations();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
CoachProfileTrainingLocations.prototype['name'] = undefined;

/**
 * @member {String} address
 */
CoachProfileTrainingLocations.prototype['address'] = undefined;






export default CoachProfileTrainingLocations;

