/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CoachPaymentMethod model module.
 * @module model/CoachPaymentMethod
 * @version 1.0.12
 */
class CoachPaymentMethod {
    /**
     * Constructs a new <code>CoachPaymentMethod</code>.
     * @alias module:model/CoachPaymentMethod
     */
    constructor() { 
        
        CoachPaymentMethod.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CoachPaymentMethod</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CoachPaymentMethod} obj Optional instance to populate.
     * @return {module:model/CoachPaymentMethod} The populated <code>CoachPaymentMethod</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CoachPaymentMethod();

            if (data.hasOwnProperty('paymentMethodId')) {
                obj['paymentMethodId'] = ApiClient.convertToType(data['paymentMethodId'], 'String');
            }
            if (data.hasOwnProperty('brandImage')) {
                obj['brandImage'] = ApiClient.convertToType(data['brandImage'], 'String');
            }
            if (data.hasOwnProperty('cardType')) {
                obj['cardType'] = ApiClient.convertToType(data['cardType'], 'String');
            }
            if (data.hasOwnProperty('last4digits')) {
                obj['last4digits'] = ApiClient.convertToType(data['last4digits'], 'String');
            }
            if (data.hasOwnProperty('default')) {
                obj['default'] = ApiClient.convertToType(data['default'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} paymentMethodId
 */
CoachPaymentMethod.prototype['paymentMethodId'] = undefined;

/**
 * @member {String} brandImage
 */
CoachPaymentMethod.prototype['brandImage'] = undefined;

/**
 * @member {String} cardType
 */
CoachPaymentMethod.prototype['cardType'] = undefined;

/**
 * @member {String} last4digits
 */
CoachPaymentMethod.prototype['last4digits'] = undefined;

/**
 * @member {Boolean} default
 */
CoachPaymentMethod.prototype['default'] = undefined;






export default CoachPaymentMethod;

