/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CoachAvailabilityLocation from './CoachAvailabilityLocation';

/**
 * The CoachAvailability model module.
 * @module model/CoachAvailability
 * @version 1.0.7
 */
class CoachAvailability {
    /**
     * Constructs a new <code>CoachAvailability</code>.
     * @alias module:model/CoachAvailability
     * @param date {String} 
     * @param startTime {Date} 
     * @param endTime {String} 
     * @param location {module:model/CoachAvailabilityLocation} 
     * @param repetition {module:model/CoachAvailability.RepetitionEnum} 
     */
    constructor(date, startTime, endTime, location, repetition) { 
        
        CoachAvailability.initialize(this, date, startTime, endTime, location, repetition);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, date, startTime, endTime, location, repetition) { 
        obj['date'] = date;
        obj['startTime'] = startTime;
        obj['endTime'] = endTime;
        obj['location'] = location;
        obj['repetition'] = repetition;
    }

    /**
     * Constructs a <code>CoachAvailability</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CoachAvailability} obj Optional instance to populate.
     * @return {module:model/CoachAvailability} The populated <code>CoachAvailability</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CoachAvailability();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('startTime')) {
                obj['startTime'] = ApiClient.convertToType(data['startTime'], 'Date');
            }
            if (data.hasOwnProperty('endTime')) {
                obj['endTime'] = ApiClient.convertToType(data['endTime'], 'String');
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = CoachAvailabilityLocation.constructFromObject(data['location']);
            }
            if (data.hasOwnProperty('repetition')) {
                obj['repetition'] = ApiClient.convertToType(data['repetition'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} date
 */
CoachAvailability.prototype['date'] = undefined;

/**
 * @member {Date} startTime
 */
CoachAvailability.prototype['startTime'] = undefined;

/**
 * @member {String} endTime
 */
CoachAvailability.prototype['endTime'] = undefined;

/**
 * @member {module:model/CoachAvailabilityLocation} location
 */
CoachAvailability.prototype['location'] = undefined;

/**
 * @member {module:model/CoachAvailability.RepetitionEnum} repetition
 */
CoachAvailability.prototype['repetition'] = undefined;





/**
 * Allowed values for the <code>repetition</code> property.
 * @enum {String}
 * @readonly
 */
CoachAvailability['RepetitionEnum'] = {

    /**
     * value: "Repeats weekly"
     * @const
     */
    "Repeats weekly": "Repeats weekly",

    /**
     * value: "Repeats monthly"
     * @const
     */
    "Repeats monthly": "Repeats monthly",

    /**
     * value: "Does not repeat"
     * @const
     */
    "Does not repeat": "Does not repeat"
};



export default CoachAvailability;

