/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CoachProfileSettingsPrivacyResetPassword model module.
 * @module model/CoachProfileSettingsPrivacyResetPassword
 * @version 1.0.12
 */
class CoachProfileSettingsPrivacyResetPassword {
    /**
     * Constructs a new <code>CoachProfileSettingsPrivacyResetPassword</code>.
     * @alias module:model/CoachProfileSettingsPrivacyResetPassword
     * @param currentPassword {String} 
     * @param newPassword1 {String} 
     * @param newPassword2 {String} 
     */
    constructor(currentPassword, newPassword1, newPassword2) { 
        
        CoachProfileSettingsPrivacyResetPassword.initialize(this, currentPassword, newPassword1, newPassword2);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, currentPassword, newPassword1, newPassword2) { 
        obj['currentPassword'] = currentPassword;
        obj['newPassword1'] = newPassword1;
        obj['newPassword2'] = newPassword2;
    }

    /**
     * Constructs a <code>CoachProfileSettingsPrivacyResetPassword</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CoachProfileSettingsPrivacyResetPassword} obj Optional instance to populate.
     * @return {module:model/CoachProfileSettingsPrivacyResetPassword} The populated <code>CoachProfileSettingsPrivacyResetPassword</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CoachProfileSettingsPrivacyResetPassword();

            if (data.hasOwnProperty('currentPassword')) {
                obj['currentPassword'] = ApiClient.convertToType(data['currentPassword'], 'String');
            }
            if (data.hasOwnProperty('newPassword1')) {
                obj['newPassword1'] = ApiClient.convertToType(data['newPassword1'], 'String');
            }
            if (data.hasOwnProperty('newPassword2')) {
                obj['newPassword2'] = ApiClient.convertToType(data['newPassword2'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} currentPassword
 */
CoachProfileSettingsPrivacyResetPassword.prototype['currentPassword'] = undefined;

/**
 * @member {String} newPassword1
 */
CoachProfileSettingsPrivacyResetPassword.prototype['newPassword1'] = undefined;

/**
 * @member {String} newPassword2
 */
CoachProfileSettingsPrivacyResetPassword.prototype['newPassword2'] = undefined;






export default CoachProfileSettingsPrivacyResetPassword;

