/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CoachProfileCertificates model module.
 * @module model/CoachProfileCertificates
 * @version 1.0.12
 */
class CoachProfileCertificates {
    /**
     * Constructs a new <code>CoachProfileCertificates</code>.
     * @alias module:model/CoachProfileCertificates
     * @param name {String} 
     * @param expiration {String} 
     * @param id {String} 
     */
    constructor(name, expiration, id) { 
        
        CoachProfileCertificates.initialize(this, name, expiration, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, expiration, id) { 
        obj['name'] = name;
        obj['expiration'] = expiration;
        obj['id'] = id;
    }

    /**
     * Constructs a <code>CoachProfileCertificates</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CoachProfileCertificates} obj Optional instance to populate.
     * @return {module:model/CoachProfileCertificates} The populated <code>CoachProfileCertificates</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CoachProfileCertificates();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('expiration')) {
                obj['expiration'] = ApiClient.convertToType(data['expiration'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
CoachProfileCertificates.prototype['name'] = undefined;

/**
 * @member {String} expiration
 */
CoachProfileCertificates.prototype['expiration'] = undefined;

/**
 * @member {String} id
 */
CoachProfileCertificates.prototype['id'] = undefined;






export default CoachProfileCertificates;

