/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CoachProfileCredentialsAndExperience model module.
 * @module model/CoachProfileCredentialsAndExperience
 * @version 1.0.0
 */
class CoachProfileCredentialsAndExperience {
    /**
     * Constructs a new <code>CoachProfileCredentialsAndExperience</code>.
     * @alias module:model/CoachProfileCredentialsAndExperience
     */
    constructor() { 
        
        CoachProfileCredentialsAndExperience.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CoachProfileCredentialsAndExperience</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CoachProfileCredentialsAndExperience} obj Optional instance to populate.
     * @return {module:model/CoachProfileCredentialsAndExperience} The populated <code>CoachProfileCredentialsAndExperience</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CoachProfileCredentialsAndExperience();

            if (data.hasOwnProperty('extensiveCoachingExperience')) {
                obj['extensiveCoachingExperience'] = ApiClient.convertToType(data['extensiveCoachingExperience'], 'String');
            }
            if (data.hasOwnProperty('industryRecognition')) {
                obj['industryRecognition'] = ApiClient.convertToType(data['industryRecognition'], 'String');
            }
            if (data.hasOwnProperty('trustedByStudents')) {
                obj['trustedByStudents'] = ApiClient.convertToType(data['trustedByStudents'], 'String');
            }
            if (data.hasOwnProperty('specializationNotes')) {
                obj['specializationNotes'] = ApiClient.convertToType(data['specializationNotes'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} extensiveCoachingExperience
 */
CoachProfileCredentialsAndExperience.prototype['extensiveCoachingExperience'] = undefined;

/**
 * @member {String} industryRecognition
 */
CoachProfileCredentialsAndExperience.prototype['industryRecognition'] = undefined;

/**
 * @member {String} trustedByStudents
 */
CoachProfileCredentialsAndExperience.prototype['trustedByStudents'] = undefined;

/**
 * @member {String} specializationNotes
 */
CoachProfileCredentialsAndExperience.prototype['specializationNotes'] = undefined;






export default CoachProfileCredentialsAndExperience;

