/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FilterSchedule model module.
 * @module model/FilterSchedule
 * @version 1.0.7
 */
class FilterSchedule {
    /**
     * Constructs a new <code>FilterSchedule</code>.
     * @alias module:model/FilterSchedule
     */
    constructor() { 
        
        FilterSchedule.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FilterSchedule</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FilterSchedule} obj Optional instance to populate.
     * @return {module:model/FilterSchedule} The populated <code>FilterSchedule</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FilterSchedule();

            if (data.hasOwnProperty('timeOfTheDay')) {
                obj['timeOfTheDay'] = ApiClient.convertToType(data['timeOfTheDay'], ['String']);
            }
            if (data.hasOwnProperty('dayOfTheWeek')) {
                obj['dayOfTheWeek'] = ApiClient.convertToType(data['dayOfTheWeek'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/FilterSchedule.TimeOfTheDayEnum>} timeOfTheDay
 */
FilterSchedule.prototype['timeOfTheDay'] = undefined;

/**
 * @member {Array.<module:model/FilterSchedule.DayOfTheWeekEnum>} dayOfTheWeek
 */
FilterSchedule.prototype['dayOfTheWeek'] = undefined;





/**
 * Allowed values for the <code>timeOfTheDay</code> property.
 * @enum {String}
 * @readonly
 */
FilterSchedule['TimeOfTheDayEnum'] = {

    /**
     * value: "Morning"
     * @const
     */
    "Morning": "Morning",

    /**
     * value: "Late Morning"
     * @const
     */
    "Late Morning": "Late Morning",

    /**
     * value: "Afternoon"
     * @const
     */
    "Afternoon": "Afternoon",

    /**
     * value: "Late Afternoon"
     * @const
     */
    "Late Afternoon": "Late Afternoon",

    /**
     * value: "Evening"
     * @const
     */
    "Evening": "Evening",

    /**
     * value: "Late Evening"
     * @const
     */
    "Late Evening": "Late Evening"
};


/**
 * Allowed values for the <code>dayOfTheWeek</code> property.
 * @enum {String}
 * @readonly
 */
FilterSchedule['DayOfTheWeekEnum'] = {

    /**
     * value: "Sun"
     * @const
     */
    "Sun": "Sun",

    /**
     * value: "Mon"
     * @const
     */
    "Mon": "Mon",

    /**
     * value: "Tue"
     * @const
     */
    "Tue": "Tue",

    /**
     * value: "Wed"
     * @const
     */
    "Wed": "Wed",

    /**
     * value: "Thu"
     * @const
     */
    "Thu": "Thu",

    /**
     * value: "Fri"
     * @const
     */
    "Fri": "Fri",

    /**
     * value: "Sat"
     * @const
     */
    "Sat": "Sat"
};



export default FilterSchedule;

