/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2008TopCities model module.
 * @module model/InlineResponse2008TopCities
 * @version 1.0.12
 */
class InlineResponse2008TopCities {
    /**
     * Constructs a new <code>InlineResponse2008TopCities</code>.
     * @alias module:model/InlineResponse2008TopCities
     */
    constructor() { 
        
        InlineResponse2008TopCities.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2008TopCities</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2008TopCities} obj Optional instance to populate.
     * @return {module:model/InlineResponse2008TopCities} The populated <code>InlineResponse2008TopCities</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2008TopCities();

            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('percentage')) {
                obj['percentage'] = ApiClient.convertToType(data['percentage'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} city
 */
InlineResponse2008TopCities.prototype['city'] = undefined;

/**
 * @member {Number} percentage
 */
InlineResponse2008TopCities.prototype['percentage'] = undefined;






export default InlineResponse2008TopCities;

