/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse20016 model module.
 * @module model/InlineResponse20016
 * @version 1.0.12
 */
class InlineResponse20016 {
    /**
     * Constructs a new <code>InlineResponse20016</code>.
     * @alias module:model/InlineResponse20016
     */
    constructor() { 
        
        InlineResponse20016.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20016</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20016} obj Optional instance to populate.
     * @return {module:model/InlineResponse20016} The populated <code>InlineResponse20016</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20016();

            if (data.hasOwnProperty('featureName')) {
                obj['featureName'] = ApiClient.convertToType(data['featureName'], 'String');
            }
            if (data.hasOwnProperty('featureId')) {
                obj['featureId'] = ApiClient.convertToType(data['featureId'], 'String');
            }
            if (data.hasOwnProperty('dateImplemented')) {
                obj['dateImplemented'] = ApiClient.convertToType(data['dateImplemented'], 'String');
            }
            if (data.hasOwnProperty('numberOfFeedback')) {
                obj['numberOfFeedback'] = ApiClient.convertToType(data['numberOfFeedback'], 'Number');
            }
            if (data.hasOwnProperty('averageRating')) {
                obj['averageRating'] = ApiClient.convertToType(data['averageRating'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} featureName
 */
InlineResponse20016.prototype['featureName'] = undefined;

/**
 * @member {String} featureId
 */
InlineResponse20016.prototype['featureId'] = undefined;

/**
 * @member {String} dateImplemented
 */
InlineResponse20016.prototype['dateImplemented'] = undefined;

/**
 * @member {Number} numberOfFeedback
 */
InlineResponse20016.prototype['numberOfFeedback'] = undefined;

/**
 * @member {Number} averageRating
 */
InlineResponse20016.prototype['averageRating'] = undefined;






export default InlineResponse20016;

