/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2006TopStates model module.
 * @module model/InlineResponse2006TopStates
 * @version 1.0.4
 */
class InlineResponse2006TopStates {
    /**
     * Constructs a new <code>InlineResponse2006TopStates</code>.
     * @alias module:model/InlineResponse2006TopStates
     */
    constructor() { 
        
        InlineResponse2006TopStates.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2006TopStates</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2006TopStates} obj Optional instance to populate.
     * @return {module:model/InlineResponse2006TopStates} The populated <code>InlineResponse2006TopStates</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2006TopStates();

            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('percentage')) {
                obj['percentage'] = ApiClient.convertToType(data['percentage'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} state
 */
InlineResponse2006TopStates.prototype['state'] = undefined;

/**
 * @member {Number} percentage
 */
InlineResponse2006TopStates.prototype['percentage'] = undefined;






export default InlineResponse2006TopStates;

