/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse2003SomeoneMessagedMe from './InlineResponse2003SomeoneMessagedMe';

/**
 * The InlineResponse2003 model module.
 * @module model/InlineResponse2003
 * @version 1.0.12
 */
class InlineResponse2003 {
    /**
     * Constructs a new <code>InlineResponse2003</code>.
     * @alias module:model/InlineResponse2003
     * @param someoneMessagedMe {module:model/InlineResponse2003SomeoneMessagedMe} 
     * @param anyoneLeftMeAReview {module:model/InlineResponse2003SomeoneMessagedMe} 
     * @param anyoneCancelledLesson {module:model/InlineResponse2003SomeoneMessagedMe} 
     * @param anyoneAcceptOrDeclineLesson {module:model/InlineResponse2003SomeoneMessagedMe} 
     * @param getNewsAnnouncementAndProductUpdates {module:model/InlineResponse2003SomeoneMessagedMe} 
     */
    constructor(someoneMessagedMe, anyoneLeftMeAReview, anyoneCancelledLesson, anyoneAcceptOrDeclineLesson, getNewsAnnouncementAndProductUpdates) { 
        
        InlineResponse2003.initialize(this, someoneMessagedMe, anyoneLeftMeAReview, anyoneCancelledLesson, anyoneAcceptOrDeclineLesson, getNewsAnnouncementAndProductUpdates);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, someoneMessagedMe, anyoneLeftMeAReview, anyoneCancelledLesson, anyoneAcceptOrDeclineLesson, getNewsAnnouncementAndProductUpdates) { 
        obj['someoneMessagedMe'] = someoneMessagedMe;
        obj['anyoneLeftMeAReview'] = anyoneLeftMeAReview;
        obj['anyoneCancelledLesson'] = anyoneCancelledLesson;
        obj['anyoneAcceptOrDeclineLesson'] = anyoneAcceptOrDeclineLesson;
        obj['getNewsAnnouncementAndProductUpdates'] = getNewsAnnouncementAndProductUpdates;
    }

    /**
     * Constructs a <code>InlineResponse2003</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2003} obj Optional instance to populate.
     * @return {module:model/InlineResponse2003} The populated <code>InlineResponse2003</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2003();

            if (data.hasOwnProperty('someoneMessagedMe')) {
                obj['someoneMessagedMe'] = InlineResponse2003SomeoneMessagedMe.constructFromObject(data['someoneMessagedMe']);
            }
            if (data.hasOwnProperty('anyoneLeftMeAReview')) {
                obj['anyoneLeftMeAReview'] = InlineResponse2003SomeoneMessagedMe.constructFromObject(data['anyoneLeftMeAReview']);
            }
            if (data.hasOwnProperty('anyoneCancelledLesson')) {
                obj['anyoneCancelledLesson'] = InlineResponse2003SomeoneMessagedMe.constructFromObject(data['anyoneCancelledLesson']);
            }
            if (data.hasOwnProperty('anyoneAcceptOrDeclineLesson')) {
                obj['anyoneAcceptOrDeclineLesson'] = InlineResponse2003SomeoneMessagedMe.constructFromObject(data['anyoneAcceptOrDeclineLesson']);
            }
            if (data.hasOwnProperty('getNewsAnnouncementAndProductUpdates')) {
                obj['getNewsAnnouncementAndProductUpdates'] = InlineResponse2003SomeoneMessagedMe.constructFromObject(data['getNewsAnnouncementAndProductUpdates']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/InlineResponse2003SomeoneMessagedMe} someoneMessagedMe
 */
InlineResponse2003.prototype['someoneMessagedMe'] = undefined;

/**
 * @member {module:model/InlineResponse2003SomeoneMessagedMe} anyoneLeftMeAReview
 */
InlineResponse2003.prototype['anyoneLeftMeAReview'] = undefined;

/**
 * @member {module:model/InlineResponse2003SomeoneMessagedMe} anyoneCancelledLesson
 */
InlineResponse2003.prototype['anyoneCancelledLesson'] = undefined;

/**
 * @member {module:model/InlineResponse2003SomeoneMessagedMe} anyoneAcceptOrDeclineLesson
 */
InlineResponse2003.prototype['anyoneAcceptOrDeclineLesson'] = undefined;

/**
 * @member {module:model/InlineResponse2003SomeoneMessagedMe} getNewsAnnouncementAndProductUpdates
 */
InlineResponse2003.prototype['getNewsAnnouncementAndProductUpdates'] = undefined;






export default InlineResponse2003;

