/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineObject3 model module.
 * @module model/InlineObject3
 * @version 1.0.4
 */
class InlineObject3 {
    /**
     * Constructs a new <code>InlineObject3</code>.
     * @alias module:model/InlineObject3
     * @param cardNumber {String} 
     * @param expirationDate {String} 
     * @param CVV {String} 
     * @param cardType {module:model/InlineObject3.CardTypeEnum} 
     */
    constructor(cardNumber, expirationDate, CVV, cardType) { 
        
        InlineObject3.initialize(this, cardNumber, expirationDate, CVV, cardType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, cardNumber, expirationDate, CVV, cardType) { 
        obj['cardNumber'] = cardNumber;
        obj['expirationDate'] = expirationDate;
        obj['CVV'] = CVV;
        obj['cardType'] = cardType;
    }

    /**
     * Constructs a <code>InlineObject3</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject3} obj Optional instance to populate.
     * @return {module:model/InlineObject3} The populated <code>InlineObject3</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject3();

            if (data.hasOwnProperty('cardNumber')) {
                obj['cardNumber'] = ApiClient.convertToType(data['cardNumber'], 'String');
            }
            if (data.hasOwnProperty('expirationDate')) {
                obj['expirationDate'] = ApiClient.convertToType(data['expirationDate'], 'String');
            }
            if (data.hasOwnProperty('CVV')) {
                obj['CVV'] = ApiClient.convertToType(data['CVV'], 'String');
            }
            if (data.hasOwnProperty('cardType')) {
                obj['cardType'] = ApiClient.convertToType(data['cardType'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} cardNumber
 */
InlineObject3.prototype['cardNumber'] = undefined;

/**
 * @member {String} expirationDate
 */
InlineObject3.prototype['expirationDate'] = undefined;

/**
 * @member {String} CVV
 */
InlineObject3.prototype['CVV'] = undefined;

/**
 * @member {module:model/InlineObject3.CardTypeEnum} cardType
 */
InlineObject3.prototype['cardType'] = undefined;





/**
 * Allowed values for the <code>cardType</code> property.
 * @enum {String}
 * @readonly
 */
InlineObject3['CardTypeEnum'] = {

    /**
     * value: "Visa"
     * @const
     */
    "Visa": "Visa",

    /**
     * value: "MasterCard"
     * @const
     */
    "MasterCard": "MasterCard",

    /**
     * value: "American Express"
     * @const
     */
    "American Express": "American Express",

    /**
     * value: "Diners Club"
     * @const
     */
    "Diners Club": "Diners Club",

    /**
     * value: "Discover"
     * @const
     */
    "Discover": "Discover",

    /**
     * value: "JCB"
     * @const
     */
    "JCB": "JCB"
};



export default InlineObject3;

