/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2014Data model module.
 * @module model/InlineResponse2014Data
 * @version 1.0.12
 */
class InlineResponse2014Data {
    /**
     * Constructs a new <code>InlineResponse2014Data</code>.
     * @alias module:model/InlineResponse2014Data
     * @param locationId {String} 
     */
    constructor(locationId) { 
        
        InlineResponse2014Data.initialize(this, locationId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, locationId) { 
        obj['locationId'] = locationId;
    }

    /**
     * Constructs a <code>InlineResponse2014Data</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2014Data} obj Optional instance to populate.
     * @return {module:model/InlineResponse2014Data} The populated <code>InlineResponse2014Data</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2014Data();

            if (data.hasOwnProperty('locationId')) {
                obj['locationId'] = ApiClient.convertToType(data['locationId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} locationId
 */
InlineResponse2014Data.prototype['locationId'] = undefined;






export default InlineResponse2014Data;

