/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse20013 model module.
 * @module model/InlineResponse20013
 * @version 1.0.0
 */
class InlineResponse20013 {
    /**
     * Constructs a new <code>InlineResponse20013</code>.
     * @alias module:model/InlineResponse20013
     */
    constructor() { 
        
        InlineResponse20013.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse20013</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse20013} obj Optional instance to populate.
     * @return {module:model/InlineResponse20013} The populated <code>InlineResponse20013</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse20013();

            if (data.hasOwnProperty('userName')) {
                obj['userName'] = ApiClient.convertToType(data['userName'], 'String');
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('coachPhoto')) {
                obj['coachPhoto'] = ApiClient.convertToType(data['coachPhoto'], 'String');
            }
            if (data.hasOwnProperty('profileOnBoardingAccepted')) {
                obj['profileOnBoardingAccepted'] = ApiClient.convertToType(data['profileOnBoardingAccepted'], 'Boolean');
            }
            if (data.hasOwnProperty('backgroundCheckAccepted')) {
                obj['backgroundCheckAccepted'] = ApiClient.convertToType(data['backgroundCheckAccepted'], 'Boolean');
            }
            if (data.hasOwnProperty('profileStatus')) {
                obj['profileStatus'] = ApiClient.convertToType(data['profileStatus'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} userName
 */
InlineResponse20013.prototype['userName'] = undefined;

/**
 * @member {String} userId
 */
InlineResponse20013.prototype['userId'] = undefined;

/**
 * @member {String} coachPhoto
 */
InlineResponse20013.prototype['coachPhoto'] = undefined;

/**
 * @member {Boolean} profileOnBoardingAccepted
 */
InlineResponse20013.prototype['profileOnBoardingAccepted'] = undefined;

/**
 * @member {Boolean} backgroundCheckAccepted
 */
InlineResponse20013.prototype['backgroundCheckAccepted'] = undefined;

/**
 * @member {module:model/InlineResponse20013.ProfileStatusEnum} profileStatus
 */
InlineResponse20013.prototype['profileStatus'] = undefined;





/**
 * Allowed values for the <code>profileStatus</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse20013['ProfileStatusEnum'] = {

    /**
     * value: "Pending"
     * @const
     */
    "Pending": "Pending",

    /**
     * value: "Declined"
     * @const
     */
    "Declined": "Declined",

    /**
     * value: "Approved"
     * @const
     */
    "Approved": "Approved"
};



export default InlineResponse20013;

