/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse4001 model module.
 * @module model/InlineResponse4001
 * @version 1.0.12
 */
class InlineResponse4001 {
    /**
     * Constructs a new <code>InlineResponse4001</code>.
     * @alias module:model/InlineResponse4001
     * @param message {String} 
     * @param errors {Array.<Object>} 
     */
    constructor(message, errors) { 
        
        InlineResponse4001.initialize(this, message, errors);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, message, errors) { 
        obj['message'] = message;
        obj['errors'] = errors;
    }

    /**
     * Constructs a <code>InlineResponse4001</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse4001} obj Optional instance to populate.
     * @return {module:model/InlineResponse4001} The populated <code>InlineResponse4001</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse4001();

            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [Object]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} message
 */
InlineResponse4001.prototype['message'] = undefined;

/**
 * @member {Array.<Object>} errors
 */
InlineResponse4001.prototype['errors'] = undefined;






export default InlineResponse4001;

