/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse2008CancellationReason model module.
 * @module model/InlineResponse2008CancellationReason
 * @version 1.0.7
 */
class InlineResponse2008CancellationReason {
    /**
     * Constructs a new <code>InlineResponse2008CancellationReason</code>.
     * @alias module:model/InlineResponse2008CancellationReason
     */
    constructor() { 
        
        InlineResponse2008CancellationReason.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse2008CancellationReason</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse2008CancellationReason} obj Optional instance to populate.
     * @return {module:model/InlineResponse2008CancellationReason} The populated <code>InlineResponse2008CancellationReason</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2008CancellationReason();

            if (data.hasOwnProperty('reasonCategory')) {
                obj['reasonCategory'] = ApiClient.convertToType(data['reasonCategory'], 'String');
            }
            if (data.hasOwnProperty('explanation')) {
                obj['explanation'] = ApiClient.convertToType(data['explanation'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} reasonCategory
 */
InlineResponse2008CancellationReason.prototype['reasonCategory'] = undefined;

/**
 * @member {String} explanation
 */
InlineResponse2008CancellationReason.prototype['explanation'] = undefined;

/**
 * @member {String} date
 */
InlineResponse2008CancellationReason.prototype['date'] = undefined;






export default InlineResponse2008CancellationReason;

