/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LocationRequestOptional model module.
 * @module model/LocationRequestOptional
 * @version 1.0.0
 */
class LocationRequestOptional {
    /**
     * Constructs a new <code>LocationRequestOptional</code>.
     * A training location resource - request
     * @alias module:model/LocationRequestOptional
     */
    constructor() { 
        
        LocationRequestOptional.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LocationRequestOptional</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LocationRequestOptional} obj Optional instance to populate.
     * @return {module:model/LocationRequestOptional} The populated <code>LocationRequestOptional</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LocationRequestOptional();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('zipcode')) {
                obj['zipcode'] = ApiClient.convertToType(data['zipcode'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} address
 */
LocationRequestOptional.prototype['address'] = undefined;

/**
 * @member {String} city
 */
LocationRequestOptional.prototype['city'] = undefined;

/**
 * @member {String} state
 */
LocationRequestOptional.prototype['state'] = undefined;

/**
 * @member {Number} zipcode
 */
LocationRequestOptional.prototype['zipcode'] = undefined;

/**
 * @member {String} name
 */
LocationRequestOptional.prototype['name'] = undefined;






export default LocationRequestOptional;

