/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StudentProfilePostExperience from './StudentProfilePostExperience';
import StudentProfilePostNotificationSettings from './StudentProfilePostNotificationSettings';
import StudentProfilePostPaymentMethods from './StudentProfilePostPaymentMethods';

/**
 * The StudentProfilePost model module.
 * @module model/StudentProfilePost
 * @version 1.0.0
 */
class StudentProfilePost {
    /**
     * Constructs a new <code>StudentProfilePost</code>.
     * Student profile info
     * @alias module:model/StudentProfilePost
     * @param studentId {String} 
     * @param profileImage {String} 
     * @param fullName {String} 
     * @param phoneNumber {String} 
     * @param dateOfBirth {String} 
     * @param emailAddress {String} 
     * @param aboutMe {String} 
     * @param experience {Array.<module:model/StudentProfilePostExperience>} 
     * @param paymentMethods {Array.<module:model/StudentProfilePostPaymentMethods>} 
     * @param notificationSettings {module:model/StudentProfilePostNotificationSettings} 
     */
    constructor(studentId, profileImage, fullName, phoneNumber, dateOfBirth, emailAddress, aboutMe, experience, paymentMethods, notificationSettings) { 
        
        StudentProfilePost.initialize(this, studentId, profileImage, fullName, phoneNumber, dateOfBirth, emailAddress, aboutMe, experience, paymentMethods, notificationSettings);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, studentId, profileImage, fullName, phoneNumber, dateOfBirth, emailAddress, aboutMe, experience, paymentMethods, notificationSettings) { 
        obj['studentId'] = studentId;
        obj['profileImage'] = profileImage;
        obj['fullName'] = fullName;
        obj['phoneNumber'] = phoneNumber;
        obj['dateOfBirth'] = dateOfBirth;
        obj['emailAddress'] = emailAddress;
        obj['aboutMe'] = aboutMe;
        obj['experience'] = experience;
        obj['paymentMethods'] = paymentMethods;
        obj['notificationSettings'] = notificationSettings;
    }

    /**
     * Constructs a <code>StudentProfilePost</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StudentProfilePost} obj Optional instance to populate.
     * @return {module:model/StudentProfilePost} The populated <code>StudentProfilePost</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StudentProfilePost();

            if (data.hasOwnProperty('studentId')) {
                obj['studentId'] = ApiClient.convertToType(data['studentId'], 'String');
            }
            if (data.hasOwnProperty('profileImage')) {
                obj['profileImage'] = ApiClient.convertToType(data['profileImage'], 'String');
            }
            if (data.hasOwnProperty('fullName')) {
                obj['fullName'] = ApiClient.convertToType(data['fullName'], 'String');
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
            if (data.hasOwnProperty('gender')) {
                obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
            }
            if (data.hasOwnProperty('dateOfBirth')) {
                obj['dateOfBirth'] = ApiClient.convertToType(data['dateOfBirth'], 'String');
            }
            if (data.hasOwnProperty('emailAddress')) {
                obj['emailAddress'] = ApiClient.convertToType(data['emailAddress'], 'String');
            }
            if (data.hasOwnProperty('aboutMe')) {
                obj['aboutMe'] = ApiClient.convertToType(data['aboutMe'], 'String');
            }
            if (data.hasOwnProperty('experience')) {
                obj['experience'] = ApiClient.convertToType(data['experience'], [StudentProfilePostExperience]);
            }
            if (data.hasOwnProperty('paymentMethods')) {
                obj['paymentMethods'] = ApiClient.convertToType(data['paymentMethods'], [StudentProfilePostPaymentMethods]);
            }
            if (data.hasOwnProperty('notificationSettings')) {
                obj['notificationSettings'] = StudentProfilePostNotificationSettings.constructFromObject(data['notificationSettings']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} studentId
 */
StudentProfilePost.prototype['studentId'] = undefined;

/**
 * @member {String} profileImage
 */
StudentProfilePost.prototype['profileImage'] = undefined;

/**
 * @member {String} fullName
 */
StudentProfilePost.prototype['fullName'] = undefined;

/**
 * @member {String} phoneNumber
 */
StudentProfilePost.prototype['phoneNumber'] = undefined;

/**
 * @member {module:model/StudentProfilePost.GenderEnum} gender
 */
StudentProfilePost.prototype['gender'] = undefined;

/**
 * @member {String} dateOfBirth
 */
StudentProfilePost.prototype['dateOfBirth'] = undefined;

/**
 * @member {String} emailAddress
 */
StudentProfilePost.prototype['emailAddress'] = undefined;

/**
 * @member {String} aboutMe
 */
StudentProfilePost.prototype['aboutMe'] = undefined;

/**
 * @member {Array.<module:model/StudentProfilePostExperience>} experience
 */
StudentProfilePost.prototype['experience'] = undefined;

/**
 * @member {Array.<module:model/StudentProfilePostPaymentMethods>} paymentMethods
 */
StudentProfilePost.prototype['paymentMethods'] = undefined;

/**
 * @member {module:model/StudentProfilePostNotificationSettings} notificationSettings
 */
StudentProfilePost.prototype['notificationSettings'] = undefined;





/**
 * Allowed values for the <code>gender</code> property.
 * @enum {String}
 * @readonly
 */
StudentProfilePost['GenderEnum'] = {

    /**
     * value: "Male"
     * @const
     */
    "Male": "Male",

    /**
     * value: "Female"
     * @const
     */
    "Female": "Female"
};



export default StudentProfilePost;

