/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StudentProfilePostPaymentMethods model module.
 * @module model/StudentProfilePostPaymentMethods
 * @version 1.0.12
 */
class StudentProfilePostPaymentMethods {
    /**
     * Constructs a new <code>StudentProfilePostPaymentMethods</code>.
     * @alias module:model/StudentProfilePostPaymentMethods
     * @param _default {Boolean} 
     * @param paymentMethodId {String} 
     */
    constructor(_default, paymentMethodId) { 
        
        StudentProfilePostPaymentMethods.initialize(this, _default, paymentMethodId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, _default, paymentMethodId) { 
        obj['default'] = _default || true;
        obj['paymentMethodId'] = paymentMethodId;
    }

    /**
     * Constructs a <code>StudentProfilePostPaymentMethods</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StudentProfilePostPaymentMethods} obj Optional instance to populate.
     * @return {module:model/StudentProfilePostPaymentMethods} The populated <code>StudentProfilePostPaymentMethods</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StudentProfilePostPaymentMethods();

            if (data.hasOwnProperty('default')) {
                obj['default'] = ApiClient.convertToType(data['default'], 'Boolean');
            }
            if (data.hasOwnProperty('paymentMethodId')) {
                obj['paymentMethodId'] = ApiClient.convertToType(data['paymentMethodId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Boolean} default
 * @default true
 */
StudentProfilePostPaymentMethods.prototype['default'] = true;

/**
 * @member {String} paymentMethodId
 */
StudentProfilePostPaymentMethods.prototype['paymentMethodId'] = undefined;






export default StudentProfilePostPaymentMethods;

