/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StudentProfileExperience from './StudentProfileExperience';
import StudentProfileNotificationSettings from './StudentProfileNotificationSettings';
import StudentProfilePaymentMethods from './StudentProfilePaymentMethods';

/**
 * The StudentProfile model module.
 * @module model/StudentProfile
 * @version 1.0.7
 */
class StudentProfile {
    /**
     * Constructs a new <code>StudentProfile</code>.
     * Student profile info
     * @alias module:model/StudentProfile
     */
    constructor() { 
        
        StudentProfile.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StudentProfile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StudentProfile} obj Optional instance to populate.
     * @return {module:model/StudentProfile} The populated <code>StudentProfile</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StudentProfile();

            if (data.hasOwnProperty('profileImage')) {
                obj['profileImage'] = ApiClient.convertToType(data['profileImage'], 'String');
            }
            if (data.hasOwnProperty('fullName')) {
                obj['fullName'] = ApiClient.convertToType(data['fullName'], 'String');
            }
            if (data.hasOwnProperty('phoneNumber')) {
                obj['phoneNumber'] = ApiClient.convertToType(data['phoneNumber'], 'String');
            }
            if (data.hasOwnProperty('gender')) {
                obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
            }
            if (data.hasOwnProperty('dateOfBirth')) {
                obj['dateOfBirth'] = ApiClient.convertToType(data['dateOfBirth'], 'String');
            }
            if (data.hasOwnProperty('emailAddress')) {
                obj['emailAddress'] = ApiClient.convertToType(data['emailAddress'], 'String');
            }
            if (data.hasOwnProperty('aboutMe')) {
                obj['aboutMe'] = ApiClient.convertToType(data['aboutMe'], 'String');
            }
            if (data.hasOwnProperty('experience')) {
                obj['experience'] = ApiClient.convertToType(data['experience'], [StudentProfileExperience]);
            }
            if (data.hasOwnProperty('paymentMethods')) {
                obj['paymentMethods'] = ApiClient.convertToType(data['paymentMethods'], [StudentProfilePaymentMethods]);
            }
            if (data.hasOwnProperty('notificationSettings')) {
                obj['notificationSettings'] = StudentProfileNotificationSettings.constructFromObject(data['notificationSettings']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} profileImage
 */
StudentProfile.prototype['profileImage'] = undefined;

/**
 * @member {String} fullName
 */
StudentProfile.prototype['fullName'] = undefined;

/**
 * @member {String} phoneNumber
 */
StudentProfile.prototype['phoneNumber'] = undefined;

/**
 * @member {module:model/StudentProfile.GenderEnum} gender
 */
StudentProfile.prototype['gender'] = undefined;

/**
 * @member {String} dateOfBirth
 */
StudentProfile.prototype['dateOfBirth'] = undefined;

/**
 * @member {String} emailAddress
 */
StudentProfile.prototype['emailAddress'] = undefined;

/**
 * @member {String} aboutMe
 */
StudentProfile.prototype['aboutMe'] = undefined;

/**
 * @member {Array.<module:model/StudentProfileExperience>} experience
 */
StudentProfile.prototype['experience'] = undefined;

/**
 * @member {Array.<module:model/StudentProfilePaymentMethods>} paymentMethods
 */
StudentProfile.prototype['paymentMethods'] = undefined;

/**
 * @member {module:model/StudentProfileNotificationSettings} notificationSettings
 */
StudentProfile.prototype['notificationSettings'] = undefined;





/**
 * Allowed values for the <code>gender</code> property.
 * @enum {String}
 * @readonly
 */
StudentProfile['GenderEnum'] = {

    /**
     * value: "Male"
     * @const
     */
    "Male": "Male",

    /**
     * value: "Female"
     * @const
     */
    "Female": "Female"
};



export default StudentProfile;

