/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LytesnapBackendApi);
  }
}(this, function(expect, LytesnapBackendApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LytesnapBackendApi.CoachReview();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CoachReview', function() {
    it('should create an instance of CoachReview', function() {
      // uncomment below and update the code to test CoachReview
      //var instance = new LytesnapBackendApi.CoachReview();
      //expect(instance).to.be.a(LytesnapBackendApi.CoachReview);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new LytesnapBackendApi.CoachReview();
      //expect(instance).to.be();
    });

    it('should have the property studentName (base name: "studentName")', function() {
      // uncomment below and update the code to test the property studentName
      //var instance = new LytesnapBackendApi.CoachReview();
      //expect(instance).to.be();
    });

    it('should have the property overallRating (base name: "overallRating")', function() {
      // uncomment below and update the code to test the property overallRating
      //var instance = new LytesnapBackendApi.CoachReview();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new LytesnapBackendApi.CoachReview();
      //expect(instance).to.be();
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instance = new LytesnapBackendApi.CoachReview();
      //expect(instance).to.be();
    });

    it('should have the property studentId (base name: "studentId")', function() {
      // uncomment below and update the code to test the property studentId
      //var instance = new LytesnapBackendApi.CoachReview();
      //expect(instance).to.be();
    });

    it('should have the property photo (base name: "photo")', function() {
      // uncomment below and update the code to test the property photo
      //var instance = new LytesnapBackendApi.CoachReview();
      //expect(instance).to.be();
    });

    it('should have the property reviewText (base name: "reviewText")', function() {
      // uncomment below and update the code to test the property reviewText
      //var instance = new LytesnapBackendApi.CoachReview();
      //expect(instance).to.be();
    });

  });

}));
