/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LytesnapBackendApi);
  }
}(this, function(expect, LytesnapBackendApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LytesnapBackendApi.StudentProfile();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StudentProfile', function() {
    it('should create an instance of StudentProfile', function() {
      // uncomment below and update the code to test StudentProfile
      //var instance = new LytesnapBackendApi.StudentProfile();
      //expect(instance).to.be.a(LytesnapBackendApi.StudentProfile);
    });

    it('should have the property profileImage (base name: "profileImage")', function() {
      // uncomment below and update the code to test the property profileImage
      //var instance = new LytesnapBackendApi.StudentProfile();
      //expect(instance).to.be();
    });

    it('should have the property fullName (base name: "fullName")', function() {
      // uncomment below and update the code to test the property fullName
      //var instance = new LytesnapBackendApi.StudentProfile();
      //expect(instance).to.be();
    });

    it('should have the property phoneNumber (base name: "phoneNumber")', function() {
      // uncomment below and update the code to test the property phoneNumber
      //var instance = new LytesnapBackendApi.StudentProfile();
      //expect(instance).to.be();
    });

    it('should have the property gender (base name: "gender")', function() {
      // uncomment below and update the code to test the property gender
      //var instance = new LytesnapBackendApi.StudentProfile();
      //expect(instance).to.be();
    });

    it('should have the property dateOfBirth (base name: "dateOfBirth")', function() {
      // uncomment below and update the code to test the property dateOfBirth
      //var instance = new LytesnapBackendApi.StudentProfile();
      //expect(instance).to.be();
    });

    it('should have the property emailAddress (base name: "emailAddress")', function() {
      // uncomment below and update the code to test the property emailAddress
      //var instance = new LytesnapBackendApi.StudentProfile();
      //expect(instance).to.be();
    });

    it('should have the property aboutMe (base name: "aboutMe")', function() {
      // uncomment below and update the code to test the property aboutMe
      //var instance = new LytesnapBackendApi.StudentProfile();
      //expect(instance).to.be();
    });

    it('should have the property experience (base name: "experience")', function() {
      // uncomment below and update the code to test the property experience
      //var instance = new LytesnapBackendApi.StudentProfile();
      //expect(instance).to.be();
    });

    it('should have the property paymentMethods (base name: "paymentMethods")', function() {
      // uncomment below and update the code to test the property paymentMethods
      //var instance = new LytesnapBackendApi.StudentProfile();
      //expect(instance).to.be();
    });

    it('should have the property notificationSettings (base name: "notificationSettings")', function() {
      // uncomment below and update the code to test the property notificationSettings
      //var instance = new LytesnapBackendApi.StudentProfile();
      //expect(instance).to.be();
    });

  });

}));
