/**
 * lytesnap-backend-api
 * This document details all the API endpoints that are consumed exclusively by lytesnap frontend.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ylin@lytesnap.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LytesnapBackendApi);
  }
}(this, function(expect, LytesnapBackendApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LytesnapBackendApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('deleteLocationLocationId', function() {
      it('should call deleteLocationLocationId successfully', function(done) {
        //uncomment below and update the code to test deleteLocationLocationId
        //instance.deleteLocationLocationId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUserCoachAvailabilityAvailabilityId', function() {
      it('should call deleteUserCoachAvailabilityAvailabilityId successfully', function(done) {
        //uncomment below and update the code to test deleteUserCoachAvailabilityAvailabilityId
        //instance.deleteUserCoachAvailabilityAvailabilityId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUserCoachProfileSettingsPayoutPaymentMethodId', function() {
      it('should call deleteUserCoachProfileSettingsPayoutPaymentMethodId successfully', function(done) {
        //uncomment below and update the code to test deleteUserCoachProfileSettingsPayoutPaymentMethodId
        //instance.deleteUserCoachProfileSettingsPayoutPaymentMethodId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUserFilterFilterName', function() {
      it('should call deleteUserFilterFilterName successfully', function(done) {
        //uncomment below and update the code to test deleteUserFilterFilterName
        //instance.deleteUserFilterFilterName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUserStudentProfileSettingsPaymentMethodsStudentIdPaymentMethodId', function() {
      it('should call deleteUserStudentProfileSettingsPaymentMethodsStudentIdPaymentMethodId successfully', function(done) {
        //uncomment below and update the code to test deleteUserStudentProfileSettingsPaymentMethodsStudentIdPaymentMethodId
        //instance.deleteUserStudentProfileSettingsPaymentMethodsStudentIdPaymentMethodId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCoach', function() {
      it('should call getCoach successfully', function(done) {
        //uncomment below and update the code to test getCoach
        //instance.getCoach(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLocation', function() {
      it('should call getLocation successfully', function(done) {
        //uncomment below and update the code to test getLocation
        //instance.getLocation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLocationLocationId', function() {
      it('should call getLocationLocationId successfully', function(done) {
        //uncomment below and update the code to test getLocationLocationId
        //instance.getLocationLocationId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserAdmin', function() {
      it('should call getUserAdmin successfully', function(done) {
        //uncomment below and update the code to test getUserAdmin
        //instance.getUserAdmin(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserAdminBookingLocationPercentage', function() {
      it('should call getUserAdminBookingLocationPercentage successfully', function(done) {
        //uncomment below and update the code to test getUserAdminBookingLocationPercentage
        //instance.getUserAdminBookingLocationPercentage(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserAdminCertificate', function() {
      it('should call getUserAdminCertificate successfully', function(done) {
        //uncomment below and update the code to test getUserAdminCertificate
        //instance.getUserAdminCertificate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserAdminCertificateCoachId', function() {
      it('should call getUserAdminCertificateCoachId successfully', function(done) {
        //uncomment below and update the code to test getUserAdminCertificateCoachId
        //instance.getUserAdminCertificateCoachId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserAdminComplaintUserId', function() {
      it('should call getUserAdminComplaintUserId successfully', function(done) {
        //uncomment below and update the code to test getUserAdminComplaintUserId
        //instance.getUserAdminComplaintUserId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserAdminDashboardFilter', function() {
      it('should call getUserAdminDashboardFilter successfully', function(done) {
        //uncomment below and update the code to test getUserAdminDashboardFilter
        //instance.getUserAdminDashboardFilter(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserAdminDashboardLocationState', function() {
      it('should call getUserAdminDashboardLocationState successfully', function(done) {
        //uncomment below and update the code to test getUserAdminDashboardLocationState
        //instance.getUserAdminDashboardLocationState(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserAdminProfile', function() {
      it('should call getUserAdminProfile successfully', function(done) {
        //uncomment below and update the code to test getUserAdminProfile
        //instance.getUserAdminProfile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserAdminProfileCheck', function() {
      it('should call getUserAdminProfileCheck successfully', function(done) {
        //uncomment below and update the code to test getUserAdminProfileCheck
        //instance.getUserAdminProfileCheck(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserAdminUserComplaints', function() {
      it('should call getUserAdminUserComplaints successfully', function(done) {
        //uncomment below and update the code to test getUserAdminUserComplaints
        //instance.getUserAdminUserComplaints(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserAdminUserFeedback', function() {
      it('should call getUserAdminUserFeedback successfully', function(done) {
        //uncomment below and update the code to test getUserAdminUserFeedback
        //instance.getUserAdminUserFeedback(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserAdminUserFeedbackFeedbackId', function() {
      it('should call getUserAdminUserFeedbackFeedbackId successfully', function(done) {
        //uncomment below and update the code to test getUserAdminUserFeedbackFeedbackId
        //instance.getUserAdminUserFeedbackFeedbackId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserAdminUsersManagement', function() {
      it('should call getUserAdminUsersManagement successfully', function(done) {
        //uncomment below and update the code to test getUserAdminUsersManagement
        //instance.getUserAdminUsersManagement(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserCoachAvailability', function() {
      it('should call getUserCoachAvailability successfully', function(done) {
        //uncomment below and update the code to test getUserCoachAvailability
        //instance.getUserCoachAvailability(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserCoachAvailabilityInfo', function() {
      it('should call getUserCoachAvailabilityInfo successfully', function(done) {
        //uncomment below and update the code to test getUserCoachAvailabilityInfo
        //instance.getUserCoachAvailabilityInfo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserCoachInsights', function() {
      it('should call getUserCoachInsights successfully', function(done) {
        //uncomment below and update the code to test getUserCoachInsights
        //instance.getUserCoachInsights(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserCoachNotifications', function() {
      it('should call getUserCoachNotifications successfully', function(done) {
        //uncomment below and update the code to test getUserCoachNotifications
        //instance.getUserCoachNotifications(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserCoachProfileCoachId', function() {
      it('should call getUserCoachProfileCoachId successfully', function(done) {
        //uncomment below and update the code to test getUserCoachProfileCoachId
        //instance.getUserCoachProfileCoachId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserCoachProfileSettingsNotifications', function() {
      it('should call getUserCoachProfileSettingsNotifications successfully', function(done) {
        //uncomment below and update the code to test getUserCoachProfileSettingsNotifications
        //instance.getUserCoachProfileSettingsNotifications(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserCoachProfileSettingsPayout', function() {
      it('should call getUserCoachProfileSettingsPayout successfully', function(done) {
        //uncomment below and update the code to test getUserCoachProfileSettingsPayout
        //instance.getUserCoachProfileSettingsPayout(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserCoachReview', function() {
      it('should call getUserCoachReview successfully', function(done) {
        //uncomment below and update the code to test getUserCoachReview
        //instance.getUserCoachReview(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserCoachSession', function() {
      it('should call getUserCoachSession successfully', function(done) {
        //uncomment below and update the code to test getUserCoachSession
        //instance.getUserCoachSession(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserFilter', function() {
      it('should call getUserFilter successfully', function(done) {
        //uncomment below and update the code to test getUserFilter
        //instance.getUserFilter(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserFilterFilterName', function() {
      it('should call getUserFilterFilterName successfully', function(done) {
        //uncomment below and update the code to test getUserFilterFilterName
        //instance.getUserFilterFilterName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserLessonsLessonId', function() {
      it('should call getUserLessonsLessonId successfully', function(done) {
        //uncomment below and update the code to test getUserLessonsLessonId
        //instance.getUserLessonsLessonId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserStudentNotificationFilter', function() {
      it('should call getUserStudentNotificationFilter successfully', function(done) {
        //uncomment below and update the code to test getUserStudentNotificationFilter
        //instance.getUserStudentNotificationFilter(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserStudentProfileSettingsBasicInfoStudentId', function() {
      it('should call getUserStudentProfileSettingsBasicInfoStudentId successfully', function(done) {
        //uncomment below and update the code to test getUserStudentProfileSettingsBasicInfoStudentId
        //instance.getUserStudentProfileSettingsBasicInfoStudentId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserStudentProfileSettingsNotificationSettingsStudentId', function() {
      it('should call getUserStudentProfileSettingsNotificationSettingsStudentId successfully', function(done) {
        //uncomment below and update the code to test getUserStudentProfileSettingsNotificationSettingsStudentId
        //instance.getUserStudentProfileSettingsNotificationSettingsStudentId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserStudentProfileSettingsPaymentMethodsStudentId', function() {
      it('should call getUserStudentProfileSettingsPaymentMethodsStudentId successfully', function(done) {
        //uncomment below and update the code to test getUserStudentProfileSettingsPaymentMethodsStudentId
        //instance.getUserStudentProfileSettingsPaymentMethodsStudentId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserStudentProfileSettingsStudentId', function() {
      it('should call getUserStudentProfileSettingsStudentId successfully', function(done) {
        //uncomment below and update the code to test getUserStudentProfileSettingsStudentId
        //instance.getUserStudentProfileSettingsStudentId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUsersLessons', function() {
      it('should call getUsersLessons successfully', function(done) {
        //uncomment below and update the code to test getUsersLessons
        //instance.getUsersLessons(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchLocationLocationId', function() {
      it('should call patchLocationLocationId successfully', function(done) {
        //uncomment below and update the code to test patchLocationLocationId
        //instance.patchLocationLocationId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchUserAdminCertificateCoachId', function() {
      it('should call patchUserAdminCertificateCoachId successfully', function(done) {
        //uncomment below and update the code to test patchUserAdminCertificateCoachId
        //instance.patchUserAdminCertificateCoachId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchUserAdminProfile', function() {
      it('should call patchUserAdminProfile successfully', function(done) {
        //uncomment below and update the code to test patchUserAdminProfile
        //instance.patchUserAdminProfile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchUserAdminProfileCheckCoachId', function() {
      it('should call patchUserAdminProfileCheckCoachId successfully', function(done) {
        //uncomment below and update the code to test patchUserAdminProfileCheckCoachId
        //instance.patchUserAdminProfileCheckCoachId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchUserCoachAvailability', function() {
      it('should call patchUserCoachAvailability successfully', function(done) {
        //uncomment below and update the code to test patchUserCoachAvailability
        //instance.patchUserCoachAvailability(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchUserCoachNotificationsRead', function() {
      it('should call patchUserCoachNotificationsRead successfully', function(done) {
        //uncomment below and update the code to test patchUserCoachNotificationsRead
        //instance.patchUserCoachNotificationsRead(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchUserCoachProfileSettings', function() {
      it('should call patchUserCoachProfileSettings successfully', function(done) {
        //uncomment below and update the code to test patchUserCoachProfileSettings
        //instance.patchUserCoachProfileSettings(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchUserCoachProfileSettingsNotifications', function() {
      it('should call patchUserCoachProfileSettingsNotifications successfully', function(done) {
        //uncomment below and update the code to test patchUserCoachProfileSettingsNotifications
        //instance.patchUserCoachProfileSettingsNotifications(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postCoachProfile', function() {
      it('should call postCoachProfile successfully', function(done) {
        //uncomment below and update the code to test postCoachProfile
        //instance.postCoachProfile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postLocation', function() {
      it('should call postLocation successfully', function(done) {
        //uncomment below and update the code to test postLocation
        //instance.postLocation(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postUserAdminCertificateCoachId', function() {
      it('should call postUserAdminCertificateCoachId successfully', function(done) {
        //uncomment below and update the code to test postUserAdminCertificateCoachId
        //instance.postUserAdminCertificateCoachId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postUserAdminDashboardFilter', function() {
      it('should call postUserAdminDashboardFilter successfully', function(done) {
        //uncomment below and update the code to test postUserAdminDashboardFilter
        //instance.postUserAdminDashboardFilter(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postUserAdminProfileCheckCoachId', function() {
      it('should call postUserAdminProfileCheckCoachId successfully', function(done) {
        //uncomment below and update the code to test postUserAdminProfileCheckCoachId
        //instance.postUserAdminProfileCheckCoachId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postUserAdminSendWarningEmail', function() {
      it('should call postUserAdminSendWarningEmail successfully', function(done) {
        //uncomment below and update the code to test postUserAdminSendWarningEmail
        //instance.postUserAdminSendWarningEmail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postUserCoachAvailability', function() {
      it('should call postUserCoachAvailability successfully', function(done) {
        //uncomment below and update the code to test postUserCoachAvailability
        //instance.postUserCoachAvailability(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postUserCoachAvailabilityInfo', function() {
      it('should call postUserCoachAvailabilityInfo successfully', function(done) {
        //uncomment below and update the code to test postUserCoachAvailabilityInfo
        //instance.postUserCoachAvailabilityInfo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postUserCoachProfileSettingsPayout', function() {
      it('should call postUserCoachProfileSettingsPayout successfully', function(done) {
        //uncomment below and update the code to test postUserCoachProfileSettingsPayout
        //instance.postUserCoachProfileSettingsPayout(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postUserCoachSession', function() {
      it('should call postUserCoachSession successfully', function(done) {
        //uncomment below and update the code to test postUserCoachSession
        //instance.postUserCoachSession(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postUserFilter', function() {
      it('should call postUserFilter successfully', function(done) {
        //uncomment below and update the code to test postUserFilter
        //instance.postUserFilter(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postUserLessonLessonIdCancelRequest', function() {
      it('should call postUserLessonLessonIdCancelRequest successfully', function(done) {
        //uncomment below and update the code to test postUserLessonLessonIdCancelRequest
        //instance.postUserLessonLessonIdCancelRequest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postUserLessons', function() {
      it('should call postUserLessons successfully', function(done) {
        //uncomment below and update the code to test postUserLessons
        //instance.postUserLessons(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postUserLessonsLessonIdProblemReport', function() {
      it('should call postUserLessonsLessonIdProblemReport successfully', function(done) {
        //uncomment below and update the code to test postUserLessonsLessonIdProblemReport
        //instance.postUserLessonsLessonIdProblemReport(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postUserStudentNotificationFilter', function() {
      it('should call postUserStudentNotificationFilter successfully', function(done) {
        //uncomment below and update the code to test postUserStudentNotificationFilter
        //instance.postUserStudentNotificationFilter(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postUserStudentProfileSettingsProfileCreate', function() {
      it('should call postUserStudentProfileSettingsProfileCreate successfully', function(done) {
        //uncomment below and update the code to test postUserStudentProfileSettingsProfileCreate
        //instance.postUserStudentProfileSettingsProfileCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putUserAdminBanUser', function() {
      it('should call putUserAdminBanUser successfully', function(done) {
        //uncomment below and update the code to test putUserAdminBanUser
        //instance.putUserAdminBanUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putUserAdminUnbanUser', function() {
      it('should call putUserAdminUnbanUser successfully', function(done) {
        //uncomment below and update the code to test putUserAdminUnbanUser
        //instance.putUserAdminUnbanUser(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putUserCoachAvailabilityOptions', function() {
      it('should call putUserCoachAvailabilityOptions successfully', function(done) {
        //uncomment below and update the code to test putUserCoachAvailabilityOptions
        //instance.putUserCoachAvailabilityOptions(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putUserCoachProfile', function() {
      it('should call putUserCoachProfile successfully', function(done) {
        //uncomment below and update the code to test putUserCoachProfile
        //instance.putUserCoachProfile(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putUserCoachProfileSettingsDisable', function() {
      it('should call putUserCoachProfileSettingsDisable successfully', function(done) {
        //uncomment below and update the code to test putUserCoachProfileSettingsDisable
        //instance.putUserCoachProfileSettingsDisable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putUserCoachProfileSettingsEnable', function() {
      it('should call putUserCoachProfileSettingsEnable successfully', function(done) {
        //uncomment below and update the code to test putUserCoachProfileSettingsEnable
        //instance.putUserCoachProfileSettingsEnable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putUserCoachProfileSettingsNotifications', function() {
      it('should call putUserCoachProfileSettingsNotifications successfully', function(done) {
        //uncomment below and update the code to test putUserCoachProfileSettingsNotifications
        //instance.putUserCoachProfileSettingsNotifications(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putUserCoachProfileSettingsPayoutPaymentMethodId', function() {
      it('should call putUserCoachProfileSettingsPayoutPaymentMethodId successfully', function(done) {
        //uncomment below and update the code to test putUserCoachProfileSettingsPayoutPaymentMethodId
        //instance.putUserCoachProfileSettingsPayoutPaymentMethodId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putUserCoachSession', function() {
      it('should call putUserCoachSession successfully', function(done) {
        //uncomment below and update the code to test putUserCoachSession
        //instance.putUserCoachSession(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putUserStudentNotificationFilterStudentId', function() {
      it('should call putUserStudentNotificationFilterStudentId successfully', function(done) {
        //uncomment below and update the code to test putUserStudentNotificationFilterStudentId
        //instance.putUserStudentNotificationFilterStudentId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putUserStudentProfileSettingsBasicInfo', function() {
      it('should call putUserStudentProfileSettingsBasicInfo successfully', function(done) {
        //uncomment below and update the code to test putUserStudentProfileSettingsBasicInfo
        //instance.putUserStudentProfileSettingsBasicInfo(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putUserStudentProfileSettingsDisable', function() {
      it('should call putUserStudentProfileSettingsDisable successfully', function(done) {
        //uncomment below and update the code to test putUserStudentProfileSettingsDisable
        //instance.putUserStudentProfileSettingsDisable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putUserStudentProfileSettingsEnable', function() {
      it('should call putUserStudentProfileSettingsEnable successfully', function(done) {
        //uncomment below and update the code to test putUserStudentProfileSettingsEnable
        //instance.putUserStudentProfileSettingsEnable(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putUserStudentProfileSettingsNotificationSettings', function() {
      it('should call putUserStudentProfileSettingsNotificationSettings successfully', function(done) {
        //uncomment below and update the code to test putUserStudentProfileSettingsNotificationSettings
        //instance.putUserStudentProfileSettingsNotificationSettings(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putUserStudentProfileSettingsPayment', function() {
      it('should call putUserStudentProfileSettingsPayment successfully', function(done) {
        //uncomment below and update the code to test putUserStudentProfileSettingsPayment
        //instance.putUserStudentProfileSettingsPayment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putUserStudentProfileSettingsPaymentMethodsStudentIdPaymentMethodId', function() {
      it('should call putUserStudentProfileSettingsPaymentMethodsStudentIdPaymentMethodId successfully', function(done) {
        //uncomment below and update the code to test putUserStudentProfileSettingsPaymentMethodsStudentIdPaymentMethodId
        //instance.putUserStudentProfileSettingsPaymentMethodsStudentIdPaymentMethodId(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
